on: [push]

jobs:
  pwa_to_apk_job:
    runs-on: ubuntu-latest
    name: PWA to APK
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # Running PWA to apk action for apk generation
      - name: Running PWA2Apk
        uses: ./.github/actions/pwa2Apk
        with:
          project-root-folder: "."
        # This one below is a seperate action which I'm using for releasing apk
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            '*.apk'
            '*.aab' 
          # Selecting all the apk, aab files
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v1.0.0 # this is used in releases and has nothing to do with the pwa-to-apk-action
          # it is only used in softprops/action-gh-release action
